In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics

In [117]:
df = pd.read_csv(r"/home/ziyad/Desktop/IA_DATA_2026_2027/02_ISMO_COURS_ET_TP/Principale/exam/Ziyad_Damghi/Ziyad_Damgui./ Ziyad_Damgui/dataset_RH.csv")

In [118]:
df.shape

(318, 16)

### Dans cette Dataset on a 318 lignes et 16 colonne

In [119]:
df.dtypes

ID_Employe                   str
Nom_Complet                  str
Genre                        str
Age                          str
Departement                  str
Ville                        str
Pays                         str
Type_Contrat                 str
Date_Embauche                str
Anciennete_Annees          int64
Salaire_MAD                  str
Note_Performance         float64
Heures_Sup_Mensuelles      int64
Satisfaction_Score       float64
Email                        str
Commentaire_Manager      float64
dtype: object

In [120]:
valeurs_num = df.select_dtypes(include= "number")
valeurs_cat = df.select_dtypes(include= "str")
for i in valeurs_num:
    manquante_num = ((valeurs_num[i].isnull().mean())*100).round(1)
    print(i ,":" ,manquante_num, "%")
for j in valeurs_cat:
     manquante_cat = ((valeurs_cat[j].isnull().mean())*100).round(1)
     print(j ,":" ,manquante_cat, "%")

Anciennete_Annees : 0.0 %
Note_Performance : 6.3 %
Heures_Sup_Mensuelles : 0.0 %
Satisfaction_Score : 5.0 %
Commentaire_Manager : 100.0 %
ID_Employe : 0.0 %
Nom_Complet : 0.0 %
Genre : 0.0 %
Age : 4.7 %
Departement : 4.1 %
Ville : 2.8 %
Pays : 0.0 %
Type_Contrat : 2.8 %
Date_Embauche : 0.0 %
Salaire_MAD : 7.5 %
Email : 4.4 %

In [121]:
df['Age'] = pd.to_numeric(df['Age'] , errors= 'coerce')
df['Salaire_MAD'] = pd.to_numeric(df['Salaire_MAD'] , errors= 'coerce')

In [122]:
(df.isnull().mean() * 100).round(1).sort_values(ascending=False)

Commentaire_Manager      100.0
Salaire_MAD                8.5
Note_Performance           6.3
Age                        5.7
Satisfaction_Score         5.0
Email                      4.4
Departement                4.1
Ville                      2.8
Type_Contrat               2.8
ID_Employe                 0.0
Nom_Complet                0.0
Genre                      0.0
Pays                       0.0
Anciennete_Annees          0.0
Date_Embauche              0.0
Heures_Sup_Mensuelles      0.0
dtype: float64

In [123]:
df = df.drop_duplicates()

In [124]:

df = df.drop_duplicates(subset= "ID_Employe")

In [125]:
df.duplicated(subset="ID_Employe" , keep = False).sum()

np.int64(0)

In [126]:
df.describe()

,Age,Anciennete_Annees,Salaire_MAD,Note_Performance,Heures_Sup_Mensuelles,Satisfaction_Score,Commentaire_Manager
count,282.000000,300.000000,276.000000,282.000000,300.000000,285.000000,0.0
mean,38.255319,7.566667,9351.058080,3.479433,9.316667,5.528070,NaN
std,59.532091,5.640177,7305.867506,0.939714,12.132617,2.648276,NaN
min,-12.000000,0.000000,-12000.000000,-1.000000,0.000000,1.100000,NaN
25%,28.000000,2.000000,7396.587500,2.900000,4.000000,3.100000,NaN
50%,35.000000,7.000000,8718.350000,3.500000,8.000000,5.600000,NaN
75%,41.000000,11.000000,10209.840000,4.100000,12.000000,8.000000,NaN
max,999.000000,20.000000,99000.000000,8.000000,120.000000,10.000000,NaN

In [127]:
df.isnull().sum()

ID_Employe                 0
Nom_Complet                0
Genre                      0
Age                       18
Departement               12
Ville                      9
Pays                       0
Type_Contrat               9
Date_Embauche              0
Anciennete_Annees          0
Salaire_MAD               24
Note_Performance          18
Heures_Sup_Mensuelles      0
Satisfaction_Score        15
Email                     12
Commentaire_Manager      300
dtype: int64

In [128]:
for col in ['Age' ,"Salaire_MAD", "Note_Performance", "Satisfaction_Score"]:
    df[col] = df[col].fillna(df[col].median())
for col in ['Email']:
    df[col] = df[col].fillna('inconnu')
for col in ['Departement', 'Ville' ,'Type_Contrat']:
    df[col] = df[col].fillna(statistics.mode(df[col])
                             )

In [129]:
def outliers(serie):
    q1 , q3 = np.quantile(serie , 0.25) , np.quantile(serie , 0.75)
    iqr = q3 - q1
    borne_inf , borne_sup = q1 - 1.5 * iqr , q3 + 1.5 * iqr
    outlier = (serie > borne_sup) | (serie < borne_inf)
    return outlier

In [130]:
outlier1 = outliers(df['Age'])
df.loc[outlier1, 'Age'] = np.nan
median_age = round(df['Age'].median())
df['Age'] = df['Age'].fillna(median_age)

In [131]:
outlier2 = outliers(df['Salaire_MAD'])
df.loc[outlier2 , 'Salaire_MAD'] = np.nan
median = round(df['Salaire_MAD'].median())
df['Salaire_MAD'] = df['Salaire_MAD'].fillna(median)

In [132]:
outlier3 = outliers(df['Note_Performance'])
df.loc[outlier3 , 'Note_Performance'] = np.nan
median = round(df['Note_Performance'].median())
df['Note_Performance'] = df['Note_Performance'].fillna(median)

In [133]:
outlier4 = outliers(df['Heures_Sup_Mensuelles'])
df.loc[outlier4 , 'Heures_Sup_Mensuelles'] = np.nan
median = round(df['Heures_Sup_Mensuelles'].median())
df['Heures_Sup_Mensuelles'] = df['Heures_Sup_Mensuelles'].fillna(median)

In [134]:
df.describe()

,Age,Anciennete_Annees,Salaire_MAD,Note_Performance,Heures_Sup_Mensuelles,Satisfaction_Score,Commentaire_Manager
count,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,0.0
mean,34.510000,7.566667,8793.36590,3.465000,7.923333,5.531667,NaN
std,8.184938,5.640177,1772.41324,0.786811,5.283038,2.581040,NaN
min,18.000000,0.000000,4560.90000,1.400000,0.000000,1.100000,NaN
25%,29.000000,2.000000,7677.18250,2.900000,4.000000,3.200000,NaN
50%,35.000000,7.000000,8718.35000,3.500000,8.000000,5.600000,NaN
75%,40.000000,11.000000,9909.29750,4.000000,12.000000,7.900000,NaN
max,56.000000,20.000000,13328.81000,5.000000,24.000000,10.000000,NaN

In [135]:
print(df['Age'].dtype)
print(df['Salaire_MAD'].dtype)

float64
float64

In [136]:
df['Commentaire_Manager'] = df['Commentaire_Manager'].astype(str)

In [137]:
df

,ID_Employe,Nom_Complet,Genre,Age,Departement,Ville,Pays,Type_Contrat,Date_Embauche,Anciennete_Annees,Salaire_MAD,Note_Performance,Heures_Sup_Mensuelles,Satisfaction_Score,Email,Commentaire_Manager
0,EMP0283,Younes Cherkaoui,H,29.0,Marketing,Agadir,Maroc,Stage,2014-12-07,11,8177.17,3.1,10.0,5.8,younes.cherkaoui@entreprise.ma,NaN
1,EMP0135,Soufiane El Amrani,H,32.0,Production,Marrakech,Maroc,Stage,2011-11-20,14,8297.49,3.3,6.0,5.5,soufiane.elamrani@entreprise.ma,NaN
2,EMP0246,Fouad Kabbaj,H,43.0,Ventes,Marrakech,Maroc,CDI,2005-12-07,20,11006.04,2.0,10.0,6.5,fouad.kabbaj@entreprise.ma,NaN
3,EMP0062,Karim Ziani,H,42.0,Marketing,Agadir,Maroc,Freelance,2011-10-22,14,8718.35,3.0,5.0,7.3,karim.ziani@entreprise.ma,NaN
4,EMP0097,Youssef Ouahbi,H,28.0,Support,Fès,Maroc,CDI,2017-01-29,9,7921.18,4.0,6.0,8.3,youssef.ouahbi@entreprise.ma,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,EMP0202,Khadija Mansouri,F,29.0,Production,Agadir,Maroc,CDI,2022-09-17,4,7796.60,3.3,7.0,1.7,khadija.mansouri@entreprise.ma,NaN
314,EMP0169,Nadia Guerraoui,F,35.0,Support,Meknès,Maroc,Stage,2015-08-13,11,9102.38,3.1,16.0,5.3,nadia.guerraoui@entreprise.ma,NaN
315,EMP0186,Wafae Idrissi,F,35.0,Marketing,Rabat,Maroc,Stage,2024-07-07,2,8395.96,3.8,10.0,5.6,wafae.idrissi@entreprise.ma,NaN
316,EMP0036,Asmae Fassi,F,22.0,Ventes,Rabat,Maroc,CDI,2023-04-17,3,6632.58,4.2,6.0,6.7,asmae.fassi@entreprise.ma,NaN
317,EMP0130,Khadija Naciri,F,51.0,Production,Fès,Maroc,Stage,2022-08-10,4,7472.22,3.7,10.0,2.4,khadija.naciri@entreprise.ma,NaN

In [138]:
df.isnull().sum()

ID_Employe                 0
Nom_Complet                0
Genre                      0
Age                        0
Departement                0
Ville                      0
Pays                       0
Type_Contrat               0
Date_Embauche              0
Anciennete_Annees          0
Salaire_MAD                0
Note_Performance           0
Heures_Sup_Mensuelles      0
Satisfaction_Score         0
Email                      0
Commentaire_Manager      300
dtype: int64

In [139]:
df.to_csv('dataset_clean.csv' , index= False)